import sqlite3
from datetime import datetime


connection_db = sqlite3.connect(r'xxeve_logistic.db')

regions_fields = {'region_id':      ['INTEGER', 'PRIMARY KEY', 'NOT NULL'],
                  'name':           ['TEXT'],
                  'description':    ['TEXT'],
                  'create_date':    ['TEXT', 'NOT NULL'],
                  'create_by':      ['TEXT', 'NOT NULL']}

constellations_fields = {'constellation_id':    ['INTEGER', 'PRIMARY KEY', 'NOT NULL'],
                         'region_id':           ['INTEGER', 'NOT NULL', 'REFERENCES regions(region_id)'],
                         'name':                ['TEXT'],
                         'position_x':          ['REAL', 'NOT NULL'],
                         'position_y':          ['REAL', 'NOT NULL'],
                         'position_z':          ['REAL', 'NOT NULL'],
                         'create_date':         ['TEXT', 'NOT NULL'],
                         'create_by':           ['TEXT', 'NOT NULL']}

systems_fields = {'system_id':              ['INTEGER', 'PRIMARY KEY', 'NOT NULL'],
                  'constellation_id':       ['INTEGER', 'NOT NULL', 'REFERENCES constellations(constellation_id)'],
                  'name':                   ['TEXT'],
                  'security_status':        ['REAL', 'NOT NULL'],
                  'security_class':         ['TEXT'],
                  'radius':                 ['REAL'],
                  'position_x':             ['REAL', 'NOT NULL'],
                  'position_y':             ['REAL', 'NOT NULL'],
                  'position_z':             ['REAL', 'NOT NULL'],
                  'regional':               ['INTEGER'],
                  'solar_system_name_id':   ['INTEGER'],
                  'hub':                    ['INTEGER'],
                  'fringe':                 ['INTEGER'],
                  'corridor':               ['INTEGER'],
                  'sun_type_id':            ['INTEGER'],
                  'wormhole_class_id':      ['INTEGER'],
                  'international':          ['INTEGER'],
                  'luminosity':             ['REAL'],
                  'stargates_number':       ['INTEGER'],
                  'planets_number':         ['INTEGER'],
                  'create_date':            ['TEXT', 'NOT NULL'],
                  'create_by':              ['TEXT', 'NOT NULL']}

market_groups_fields = {'market_group_id':  ['INTEGER', 'PRIMARY KEY', 'NOT NULL'],
                        'description':      ['TEXT'],
                        'name':             ['TEXT'],
                        'parent_group_id':  ['INTEGER'],
                        'hasTypes':         ['TEXT'],
                        'icon_id':          ['INTEGER'],
                        'create_date':      ['TEXT', 'NOT NULL'],
                        'create_by':        ['TEXT', 'NOT NULL']}

categories_fields = {'category_id':      ['INTEGER', 'PRIMARY KEY', 'NOT NULL'],
                     'name':             ['TEXT'],
                     'published':        ['TEXT'],
                     'icon_id':          ['INTEGER'],
                     'create_date':      ['TEXT', 'NOT NULL'],
                     'create_by':        ['TEXT', 'NOT NULL']}

groups_fields = {'group_id':                ['INTEGER', 'PRIMARY KEY', 'NOT NULL'],
                 'category_id':             ['INTEGER', 'NOT NULL', 'REFERENCES categories(category_id)'],
                 'name':                    ['TEXT'],
                 'useBasePrice':            ['INTEGER'],
                 'anchorable':              ['INTEGER'],
                 'anchored':                ['INTEGER'],
                 'published':               ['INTEGER'],
                 'fittableNonSingleton':    ['INTEGER'],
                 'icon_id':                 ['INTEGER'],
                 'create_date':             ['TEXT', 'NOT NULL'],
                 'create_by':               ['TEXT', 'NOT NULL']}

types_fields = {'type_id':                  ['INTEGER', 'PRIMARY KEY', 'NOT NULL'],
                'market_group_id':          ['INTEGER', 'REFERENCES market_groups(market_group_id)'],
                'group_id':                 ['INTEGER', 'NOT NULL', 'REFERENCES groups(group_id)'],
                'name':                     ['TEXT'],
                'volume':                   ['REAL'],
                'portion_size':             ['INTEGER'],
                'mass':                     ['INTEGER'],
                'description':              ['TEXT'],
                'capacity':                 ['INTEGER'],
                'icon_id':                  ['INTEGER'],
                'radius':                   ['REAL'],
                'sof_material_set_id':      ['INTEGER'],
                'race_id':                  ['INTEGER'],
                'variation_parent_type_id': ['INTEGER'],
                'meta_group_id':            ['INTEGER'],
                'published':                ['TEXT'],
                'base_price':               ['REAL'],
                'graphic_id':               ['INTEGER'],
                'sof_faction_name':         ['TEXT'],
                'sound_id':                 ['INTEGER'],
                'faction_id':               ['INTEGER'],
                'masteries':                ['TEXT'],
                'create_date':              ['TEXT', 'NOT NULL'],
                'create_by':                ['TEXT', 'NOT NULL']}


orders_fields = {'order_id':        ['INTEGER', 'PRIMARY KEY', 'NOT NULL'],
                 'location_id':     ['INTEGER', 'NOT NULL'],
                 'system_id':       ['INTEGER', 'NOT NULL', 'REFERENCES systems(system_id)'],
                 'type_id':         ['INTEGER', 'NOT NULL', 'REFERENCES types(type_id)'],
                 'duration':        ['INTEGER'],
                 'is_buy_order':    ['INTEGER'],
                 'issued':          ['TEXT'],
                 'min_volume':      ['INTEGER'],
                 'price':           ['INTEGER'],
                 'range':           ['INTEGER'],
                 'volume_remain':   ['INTEGER'],
                 "volume_total":    ['INTEGER'],
                 'create_date':     ['TEXT', 'NOT NULL'],
                 'create_by':       ['TEXT', 'NOT NULL']}

snap_statistic_systems_fields = {'system_id':      ['INTEGER', 'NOT NULL', 'REFERENCES systems(system_id)'],
                                 'snap_id':        ['INTEGER', 'NOT NULL'],
                                 'ship_jumps':     ['INTEGER', 'NOT NULL'],
                                 'npc_kills':      ['INTEGER', 'NOT NULL'],
                                 'pod_kills':      ['INTEGER', 'NOT NULL'],
                                 'ship_kills':     ['INTEGER', 'NOT NULL'],
                                 'create_date':    ['TEXT', 'NOT NULL'],
                                 'create_by':      ['TEXT', 'NOT NULL'],
                                 'PRIMARY KEY':    ['(system_id, snap_id)']}

entity_list_fields = {'entity_code':    ['TEXT', 'NOT NULL'],
                      'entity_id':      ['INTEGER', 'NOT NULL'],
                      'create_date':    ['TEXT', 'NOT NULL'],
                      'create_by':      ['TEXT', 'NOT NULL'],
                      'PRIMARY KEY':    ['(entity_code, entity_id)']}

killmails_fields = {'killmail_id':       ['INTEGER', 'PRIMARY KEY', 'NOT NULL'],
                    'location_id':       ['INTEGER', 'NOT NULL'],
                    'fitted_value':      ['REAL', 'NOT NULL'],
                    'dropped_value':     ['REAL', 'NOT NULL'],
                    'destroyed_value':   ['REAL', 'NOT NULL'],
                    'total_value':       ['REAL', 'NOT NULL'],
                    'points':            ['INTEGER', 'NOT NULL'],
                    'npc':               ['INTEGER', 'NOT NULL'],
                    'solo':              ['INTEGER', 'NOT NULL'],
                    'awox':              ['INTEGER', 'NOT NULL'],
                    'killmail_time':     ['TEXT', 'NOT NULL'],
                    'system_id':         ['INTEGER', 'NOT NULL'],
                    'system_name':       ['TEXT', 'NOT NULL'],
                    'create_date':       ['TEXT', 'NOT NULL'],
                    'create_by':         ['TEXT', 'NOT NULL']}

attackers_fields = {'attacker_id':                  ['INTEGER', 'NOT NULL'],
                    'killmail_id':                  ['INTEGER', 'REFERENCES killmails(killmail_id)'],
                    'attacker_alliance_id':         ['INTEGER'],
                    'attacker_alliance_name':       ['TEXT'],
                    'attacker_character_id':        ['INTEGER'],
                    'attacker_corporation_id':      ['INTEGER'],
                    'attacker_corporation_name':    ['TEXT'],
                    'attacker_damage_done':         ['INTEGER'],
                    'attacker_final_blow':          ['INTEGER'],
                    'attacker_security_status':     ['INTEGER', 'NOT NULL'],
                    'attacker_ship_id':             ['INTEGER'],
                    'attacker_ship_name':           ['TEXT'],
                    'attacker_weapon_type_id':      ['INTEGER'],
                    'attacker_weapon_name':         ['TEXT'],
                    'create_date':                  ['TEXT', 'NOT NULL'],
                    'create_by':                    ['TEXT', 'NOT NULL'],
                    'PRIMARY KEY':                  ['(attacker_id, killmail_id)']}

victims_fields = {'victim_id':                  ['INTEGER', 'NOT NULL'],
                  'killmail_id':                ['INTEGER', 'REFERENCES killmails(killmail_id)'],
                  'victim_alliance_id':         ['INTEGER'],
                  'victim_alliance_name':       ['TEXT'],
                  'victim_corporation_id':      ['INTEGER'],
                  'victim_corporation_name':    ['TEXT'],
                  'victim_character_id':        ['INTEGER'],
                  'victim_damage_taken':        ['INTEGER'],
                  'victim_position_x':          ['REAL', 'NOT NULL'],
                  'victim_position_y':          ['REAL', 'NOT NULL'],
                  'victim_position_z':          ['REAL', 'NOT NULL'],
                  'victim_ship_id':             ['INTEGER'],
                  'victim_ship_name':           ['TEXT'],
                  'create_date':                ['TEXT', 'NOT NULL'],
                  'create_by':                  ['TEXT', 'NOT NULL'],
                  'PRIMARY KEY':                ['(victim_id, killmail_id)']}

characters_fields = {'character_id':        ['INTEGER', 'PRIMARY KEY'],
                     'birthday':            ['TEXT'],
                     'name':                ['TEXT'],
                     'alliance_id':         ['INTEGER'],
                     'alliance_name':       ['TEXT'],
                     'corporation_id':      ['INTEGER'],
                     'corporation_name':    ['TEXT'],
                     'security_status':     ['REAL', 'NOT NULL'],
                     'bloodline_id':        ['INTEGER'],
                     'description':         ['TEXT'],
                     'title':               ['TEXT'],
                     'is_dangerous':        ['INTEGER', 'NOT NULL', 'DEFAULT 0'],
                     'create_date':         ['TEXT', 'NOT NULL'],
                     'create_by':           ['TEXT', 'NOT NULL']}

characters_killmails_fields = {'character_id':  ['INTEGER'],
                               'killmail_id':   ['INTEGER'],
                               'is_killer':     ['INTEGER', 'NOT NULL'],
                               'is_looser':     ['INTEGER', 'NOT NULL'],
                               'create_date':   ['TEXT', 'NOT NULL'],
                               'create_by':     ['TEXT', 'NOT NULL'],
                               'PRIMARY KEY':   ['(character_id, killmail_id)']}

corporations_fields = {'corporation_id':            ['INTEGER', 'PRIMARY KEY'],
                       'alliance_id':               ['INTEGER'],
                       'name':                      ['TEXT', 'NOT NULL'],
                       'ticker':                    ['TEXT', 'NOT NULL'],
                       'ceo_id':                    ['INTEGER', 'NOT NULL'],
                       'creator_id':                ['INTEGER', 'NOT NULL'],
                       'date_founded':              ['TEXT'],
                       'description':               ['TEXT'],
                       'home_station_id':           ['INTEGER'],
                       'member_count':              ['INTEGER', 'NOT NULL'],
                       'shares':                    ['INTEGER'],
                       'tax_rate':                  ['INTEGER'],
                       'url':                       ['TEXT'],
                       'war_eligible':              ['INTEGER'],
                       'is_dangerous':              ['INTEGER', 'NOT NULL', 'DEFAULT 0'],
                       'create_date':               ['TEXT', 'NOT NULL'],
                       'create_by':                 ['TEXT', 'NOT NULL']}

corporations_killmails_fields = {'corporation_id':  ['INTEGER'],
                                 'killmail_id':     ['INTEGER'],
                                 'create_date':     ['TEXT', 'NOT NULL'],
                                 'create_by':       ['TEXT', 'NOT NULL'],
                                 'PRIMARY KEY':     ['(corporation_id, killmail_id)']}

alliances_fields = {'alliance_id':              ['INTEGER', 'PRIMARY KEY'],
                    'name':                     ['TEXT', 'NOT NULL'],
                    'ticker':                   ['TEXT', 'NOT NULL'],
                    'creator_corporation_id':   ['INTEGER', 'NOT NULL'],
                    'creator_id':               ['INTEGER', 'NOT NULL'],
                    'date_founded':             ['TEXT', 'NOT NULL'],
                    'description':              ['TEXT'],
                    'executor_corporation_id':  ['INTEGER', 'NOT NULL'],
                    'create_date':              ['TEXT', 'NOT NULL'],
                    'create_by':                ['TEXT', 'NOT NULL']}

alliances_corporations_fields = {'alliance_id':    ['INTEGER'],
                                 'corporation_id': ['INTEGER'],
                                 'create_date':    ['TEXT', 'NOT NULL'],
                                 'create_by':      ['TEXT', 'NOT NULL'],
                                 'PRIMARY KEY':    ['(alliance_id, corporation_id)']}

